services:
 network-deploy-service:
  networks:
       - bankingsolutions
       
 microservice-base-config:
  extends:
   service: network-deploy-service
  deploy:
      resources:
        limits:
          memory: 700m
    
 microservice-configserver-config:
  extends: microservice-base-config
  depends_on:
   configserver:
    condition: service_helathy
   eurekaserver:
    condition: service_helathy
  environment:
      SPRING_PROFILES_ACTIVE: qa
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
   